# Generated by Django 5.1.2 on 2024-10-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='joined_date',
            field=models.DateField(auto_now=True),
        ),
    ]
